tunnel: e1da5b3b-f275-4fc0-a865-097aea9849e1
# La ubicación del archivo de credenciales puede establecerse mediante la
# variable de entorno `CLOUDFLARED_CREDENTIALS_FILE` o caer por defecto en la
# ruta `~/.cloudflared/cred.json`.
credentials-file: ${CLOUDFLARED_CREDENTIALS_FILE:-~/.cloudflared/cred.json}

ingress:
  - hostname: ourhabits.org
    service: http://localhost:3000
  - service: http_status:404
